version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app
    develop:
      watch:
        - path: ./app
          action: sync
          target: /app
        - path: ./requirements.txt
          action: rebuild
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: 8000
