# Generated by Django 5.2.6 on 2025-09-13 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_expense_user_alter_book_distribution_expense_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Tickets'},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
